version: "3.8"
services:
  db:
    container_name: database
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    volumes:
      - ./volumes/db/data:/var/lib/database/data

  app:
    build:
      context: .
      args:
        - DEBUG=${DEBUG}
    container_name: backend
    env_file: .env
    restart: always
    volumes:
      - ./src:/app
      - ./volumes/media:/media
      - ./volumes/static:/static
    depends_on:
      - db
    ports:
      - 8000:8000
    command: gunicorn --bind 0.0.0.0:8000 --timeout 600 --log-level debug --reload
      --workers 4 core.wsgi:application
